# Generated by Django 3.1 on 2020-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='010', max_length=20),
        ),
    ]
