# Generated by Django 3.0.7 on 2020-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
