version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=instar
      - POSTGRES_PASSWORD=instar1234!
      - POSTGRES_DB=instar
    ports:
      - "5432:5432"
    volumes:
      - share_database:/var/lib/postgresql
      - share_database:/var/log

  web:
    container_name: web
    build:
      context: ..
      dockerfile: config/Dockerfile
    expose:
      - "8000"
    entrypoint: /bin/sh -c "config/runserver.sh"
    depends_on:
      - db
    volumes:
      - share_files:/app/staticfiles
      - share_files:/app/upload

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: config/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - share_files:/app/staticfiles
      - share_files:/app/upload


volumes:
  share_files:
  share_database:
