# Generated by Django 3.0.7 on 2020-06-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0002_auto_20200619_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
