# Generated by Django 3.0.7 on 2020-06-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0003_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_comment', to='app_comment.Comment'),
        ),
    ]
