# Generated by Django 3.0.7 on 2020-06-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreport',
            name='result',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
