# Generated by Django 3.0.7 on 2020-06-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0002_auto_20200620_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
