# Generated by Django 3.1 on 2020-08-11 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_comment', '0002_auto_20200811_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to', to='api_comment.comment'),
        ),
    ]
